# Generated by Django 2.2.7 on 2019-12-06 06:41

from django.db import migrations, models
import spots.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('m2', models.FloatField(validators=[spots.validators.validate_m2])),
                ('mail', models.EmailField(max_length=50)),
            ],
        ),
    ]
